# -*- coding: utf-8 -*-
"""Catalogue des scenarios de test : source unique pour le plan de tests et le rapport final."""

# (ID, titre, preconditions, etapes, jeu de donnees, resultat attendu, critere de validation, priorite, automatisation)
UI = [
    ("UI-01", "Inscription valide (formulaire complet)",
     "Navigateur ouvert, /form accessible",
     "1. Ouvrir /form\n2. Saisir prénom, nom, poste\n3. Choisir niveau d'études, sexe, expérience, date\n4. Cliquer sur Submit",
     "3 jeux : Yassine Essalhi / Salma Benani / Omar El Idrissi (voir TestData)",
     "Page /thanks affichée avec le message de succès",
     "Titre « Thanks for submitting your form » et alerte « The form was successfully submitted! »",
     "Haute", "FormTests.inscriptionValide"),
    ("UI-02", "Soumission avec champs vides",
     "/form accessible",
     "1. Ouvrir /form\n2. Cliquer sur Submit sans rien saisir",
     "Aucune donnée",
     "Comportement réel de Formy : la soumission aboutit (pas de validation côté client)",
     "Message de succès affiché (constat documenté dans le rapport final)",
     "Moyenne", "FormTests.soumissionFormulaireVide"),
    ("UI-03", "Liste déroulante « années d'expérience »",
     "/form accessible",
     "1. Ouvrir /form\n2. Sélectionner chaque option du menu",
     "0-1, 2-4, 5-9, 10+",
     "L'option choisie devient l'option sélectionnée",
     "getFirstSelectedOption = libellé choisi",
     "Moyenne", "FormTests.listeDeroulanteExperience"),
    ("UI-04", "Ouverture et fermeture du modal (Close)",
     "/modal accessible",
     "1. Ouvrir /modal\n2. Cliquer sur « Open modal »\n3. Cliquer sur Close",
     "-",
     "Le pop-up apparaît puis disparaît",
     "Modal invisible au départ, visible avec le titre « Modal title », invisible après Close",
     "Haute", "ModalTests.ouvrirPuisFermerLeModal"),
    ("UI-05", "Bouton OK du modal",
     "/modal accessible",
     "1. Ouvrir le modal\n2. Cliquer sur OK\n3. Cliquer sur Close",
     "-",
     "OK n'a pas de gestionnaire (pas de data-dismiss) : le modal reste ouvert",
     "Modal toujours affiché après OK, fermé après Close",
     "Basse", "ModalTests.boutonOkSansEffetDeFermeture"),
    ("UI-06", "Alerte JavaScript",
     "/switch-window accessible",
     "1. Ouvrir /switch-window\n2. Cliquer sur « Alert »\n3. Lire puis accepter l'alerte",
     "-",
     "Alerte « This is a test alert! » acceptée",
     "Texte de l'alerte conforme, page toujours utilisable",
     "Haute", "SwitchWindowTests.alerteJavaScriptAcceptee"),
    ("UI-07", "Nouvel onglet",
     "/switch-window accessible",
     "1. Cliquer sur « New Tab »\n2. Basculer sur le nouvel onglet\n3. Le fermer et revenir",
     "-",
     "Deux fenêtres puis retour à une seule",
     "2 handles après le clic, URL du nouvel onglet = site Formy, retour sur /switch-window",
     "Moyenne", "SwitchWindowTests.nouvelOnglet"),
    ("UI-08", "Navigation par le menu déroulant",
     "/dropdown accessible",
     "1. Déplier « Dropdown button »\n2. Choisir une entrée",
     "Buttons, Checkbox, Radio Button, Modal",
     "Navigation vers la page choisie",
     "URL contient le fragment attendu ; menu de 10 entrées ou plus",
     "Moyenne", "ElementsTests.menuDeroulantNavigation"),
    ("UI-09", "Boutons radio exclusifs",
     "/radiobutton accessible",
     "1. Vérifier l'option 1 cochée par défaut\n2. Cocher l'option 3",
     "Options 1 à 3",
     "Une seule option sélectionnée à la fois",
     "Option 3 cochée, options 1 et 2 décochées",
     "Haute", "ElementsTests.boutonsRadioExclusifs"),
    ("UI-10", "Cases à cocher indépendantes",
     "/checkbox accessible",
     "1. Cocher les cases 1 et 3\n2. Décocher la case 1",
     "Cases 1 à 3",
     "Chaque case change d'état indépendamment",
     "États conformes après chaque action",
     "Moyenne", "ElementsTests.casesACocher"),
    ("UI-11", "Boutons et groupe de boutons",
     "/buttons accessible",
     "1. Contrôler les boutons colorés\n2. Cliquer sur « Success »\n3. Déplier le groupe avec menu",
     "-",
     "Tous les boutons sont actifs ; le menu du groupe propose 2 liens",
     "6 boutons ou plus, tous activés, 2 entrées de menu",
     "Moyenne", "ElementsTests.boutons"),
    ("UI-12", "Champ actif / champ désactivé",
     "/enabled accessible",
     "1. Contrôler l'état des deux champs\n2. Saisir un texte dans le champ actif",
     "« texte de test »",
     "Le champ désactivé n'est pas modifiable",
     "isEnabled = false (désactivé), true (actif), valeur saisie relue",
     "Basse", "ElementsTests.champsActifEtDesactive"),
    ("UI-13", "Frames imbriqués (site tiers)",
     "the-internet.herokuapp.com joignable",
     "1. Ouvrir /nested_frames\n2. Entrer dans frame-top puis frame-left/middle/right\n3. Lire le texte",
     "LEFT, MIDDLE, RIGHT",
     "Chaque frame contient son libellé",
     "Texte lu = texte attendu (3 frames sur 3)",
     "Moyenne", "FramesTests.lireFramesDuHaut (groupe external)"),
    ("UI-14", "Frame du bas puis retour au contenu principal (site tiers)",
     "the-internet.herokuapp.com joignable",
     "1. Lire frame-bottom\n2. Revenir au contenu par défaut\n3. Lire le frame du milieu",
     "BOTTOM, MIDDLE",
     "Le changement de contexte entre frames fonctionne",
     "Textes lus conformes",
     "Basse", "FramesTests.lireFrameDuBas (groupe external)"),
    ("UI-15", "iFrame et iFrame imbriqué (page locale déterministe)",
     "Aucune (page data: autonome)",
     "1. Ouvrir la page locale\n2. Lire l'iFrame externe\n3. Lire l'iFrame imbriqué\n4. Revenir à la page parente",
     "Contenu externe / Contenu imbriqué",
     "Les deux niveaux d'iFrame sont lisibles",
     "Textes conformes, titre parent relu",
     "Haute", "FramesTests.lireIframesLocaux"),
]

API = [
    ("API-01", "GET /api/users?page=2",
     "API joignable, en-tête x-api-key",
     "GET /api/users?page=2",
     "page=2",
     "200, 6 utilisateurs, pagination cohérente",
     "Statut 200 ; page=2 ; per_page=6 ; data de 6 éléments ; schéma users-list ; durée < 3 s",
     "Haute", "UsersApiTests.listerLesUtilisateurs / Postman API-01"),
    ("API-02", "GET /api/users/2",
     "idem",
     "GET /api/users/2",
     "id=2",
     "200, utilisateur Janet Weaver",
     "Statut 200 ; first_name/last_name ; schéma user-single ; durée < 3 s",
     "Haute", "UsersApiTests.consulterUnUtilisateur / Postman API-02"),
    ("API-03", "GET /api/users/23 (inexistant)",
     "idem",
     "GET /api/users/23",
     "id=23",
     "404 et corps JSON vide",
     "Statut 404 ; pas de clé data ; durée < 3 s",
     "Haute", "UsersApiTests.utilisateurInexistant / Postman API-03"),
    ("API-04", "POST /api/users",
     "idem",
     "POST /api/users avec name et job",
     "morpheus/leader ; Yassine Essalhi/Ingénieur QA (Postman : valeurs aléatoires)",
     "201, données renvoyées avec id et createdAt (non persisté)",
     "Statut 201 ; name/job identiques ; id et createdAt présents ; schéma user-created",
     "Haute", "UsersApiTests.creerUnUtilisateur / Postman API-04"),
    ("API-05", "PUT /api/users/2",
     "idem",
     "PUT /api/users/2 avec name et job",
     "morpheus/zion resident",
     "200 avec updatedAt",
     "Statut 200 ; valeurs mises à jour ; updatedAt présent ; schéma user-updated",
     "Moyenne", "UsersApiTests.modifierUnUtilisateur / Postman API-05"),
    ("API-06", "DELETE /api/users/2",
     "idem",
     "DELETE /api/users/2",
     "id=2",
     "204 sans contenu",
     "Statut 204 ; corps vide ; durée < 3 s",
     "Moyenne", "UsersApiTests.supprimerUnUtilisateur / Postman API-06"),
    ("API-07", "POST /api/login valide",
     "idem",
     "POST /api/login",
     "eve.holt@reqres.in / cityslicka",
     "200 avec un token",
     "Statut 200 ; token non vide ; schéma login-success",
     "Moyenne", "UsersApiTests.connexionValide / Postman API-07"),
    ("API-08", "POST /api/login sans mot de passe",
     "idem",
     "POST /api/login avec email seul",
     "peter@klaven",
     "400 « Missing password »",
     "Statut 400 ; message exact ; schéma error",
     "Haute", "UsersApiTests.connexionSansMotDePasse / Postman API-08"),
]

PERF = [
    ("PERF-01", "Charge nominale : 50 utilisateurs, GET et POST",
     "JMeter 5.6 installé ; cible joignable",
     "Lancer scripts/run-jmeter.sh : 50 threads, montée en charge 10 s, 10 boucles ; GET /api/users?page=2 puis POST /api/users (CSV)",
     "jmeter/data/users.csv (40 lignes)",
     "Aucune erreur ; temps de réponse stables",
     "Erreurs < 1 % ; P95 < 3 000 ms ; débit relevé",
     "Haute", "jmeter/reqres-load-test.jmx"),
    ("PERF-02", "Comportement face à la limitation de débit (HTTP 429)",
     "Quota Reqres entamé ou épuisé",
     "Rejouer PERF-01 sur l'API publique et observer les codes de réponse",
     "idem",
     "Les 429 sont mesurés et analysés, pas masqués",
     "Part de 429 rapportée dans le tableau de bord et dans le rapport final",
     "Haute", "reports/perf/reqres"),
]

SEC = [
    ("SEC-01", "Analyse passive ZAP de Formy (baseline)",
     "ZAP 2.17 ; cible joignable",
     "scripts/zap-scan.sh : spider (3 min max) puis analyse passive",
     "https://formy-project.herokuapp.com",
     "Rapport des alertes avec niveau de risque",
     "Rapports HTML et JSON produits ; chaque alerte classée (OWASP Top 10 / CWE)",
     "Haute", "scripts/zap-scan.sh"),
    ("SEC-02", "Recherche de réflexion XSS sur /form et /thanks",
     "Aucune",
     "Envoyer un marqueur inoffensif dans les paramètres d'URL et rechercher sa réflexion dans la réponse",
     "ZAPXSSMARK12345",
     "Marqueur non réfléchi",
     "0 occurrence du marqueur dans la page retournée",
     "Moyenne", "Contrôle manuel (curl), voir rapport"),
]

# Exigences du sujet -> scenarios
REQUIREMENTS = [
    ("E1", "Scénario formulaire login / inscription (Formy)", "UI-01, UI-02, UI-03"),
    ("E2", "Scénarios boutons et pop-ups (Formy)", "UI-04, UI-05, UI-11"),
    ("E3", "Alertes JavaScript et nouvelles fenêtres", "UI-06, UI-07"),
    ("E4", "Frames / iFrames", "UI-13, UI-14, UI-15"),
    ("E5", "Listes déroulantes et boutons radio", "UI-03, UI-08, UI-09, UI-10"),
    ("E6", "API : GET /users, POST /users, PUT /users/{id}, DELETE /users/{id}", "API-01 à API-06"),
    ("E7", "Cas négatifs et vérification du schéma JSON", "API-03, API-08 + schémas"),
    ("E8", "Postman exporté et exécuté avec Newman", "API-01 à API-08 (collection)"),
    ("E9", "Performance : au moins 50 utilisateurs, GET et POST", "PERF-01, PERF-02"),
    ("E10", "Sécurité : scan ZAP, XSS, en-têtes manquants", "SEC-01, SEC-02"),
    ("E11", "Rapports Allure (UI/API), Newman, JMeter, ZAP", "reports/"),
    ("E12", "Pipeline CI/CD (UI + API, rapports, notifications)", ".gitlab-ci.yml, Jenkinsfile"),
]
